---

- name: fetch value for virtual env environment variable
  set_fact:
    virtual_env: "{{ lookup('env', 'VIRTUAL_ENV') | default('noenv', True) }}"

- name: fetch value for virtual env exists
  set_fact:
    has_virtual_env: "{{ virtual_env != 'noenv' | bool }}"

- name: print out
  debug:
    msg: "virtual_env is {{ virtual_env }} and has_virtual_env is {{ has_virtual_env }}"

# If this playbook was triggered from sysman, we download the fastq_screen_reference genomes
# to the orchestration/local machine and then transfer them to the
# target machine, since this will be super slow to download, and we don't want to keep redoing it,
# especially when running locally.
- name: ensure directory exists locally (sysman), or at resources (miarka)
  file:
    # noqa 208
    # Adding lint exception since setting permissions on this folder is troublesome because it is done locally
    # and will be done by different users
    state: directory
    path: "{{ seqreports_fastq_screen_resource_path }}"
  delegate_to: localhost

- name: download fastq_screen genomes (please note this will be very slow), with virtual_env
  shell: "source {{ virtual_env }}/bin/activate && python roles/seqreports/files/get_fastq_screen_reference_genomes.py {{ seqreports_fastq_screen_resource_path }}"
  args:
    creates: "{{ seqreports_fastq_screen_resource_path }}/FastQ_Screen_Genomes"
  delegate_to: localhost
  when: has_virtual_env == true | bool

- name: download fastq_screen genomes (please note this will be very slow), without virtual_env
  shell: "python roles/seqreports/files/get_fastq_screen_reference_genomes.py {{ seqreports_fastq_screen_resource_path }}"
  args:
    creates: "{{ seqreports_fastq_screen_resource_path }}/FastQ_Screen_Genomes"
  delegate_to: localhost
  when: has_virtual_env == false | bool

- name: Create symlink to FastQ_Screen_Genomes (miarka only)
  file:
    src: "{{ seqreports_fastq_screen_resource_path }}/FastQ_Screen_Genomes"
    dest: "{{ seqreports_data_fastq_screen_db_path }}"
    state: link
  when: miarka_deployment | bool

