---
- name: "Check if {{ awscli_env_name }} virtual env exists"
  shell: "conda env list"
  register: "conda_envs"

- name: >
    Setup {{ awscli_env_name }} virtual env
    with python {{ python3_version }} and awscli v{{ awscli_version }}
  command: >
    conda create -n {{ nf_core_env_name }}
    -c conda-forge
    -c bioconda
    python={{ python3_version }}
    awscli={{ awscli_version }}
  when: not awscli_env_name in conda_envs.stdout|split


- name: get AWS-igenomes from git
  git:
    repo: "{{ aws_igenomes_repo }}"
    dest: "{{ aws_igenomes_dest }}"
    version: "{{ aws_igenomes_commit }}"
    force: yes

- name: set permissions to the seqreports data path
  file:
    path: "{{ aws_igenomes_dest }}/aws-igenomes.sh"
    mode: +x

- name: download iGenome
  command: "{{ aws_igenomes_dest }}/aws-igenomes.sh 
    -g {{ item.genome }}
    -s {{ item.source }}
    -b {{ item.build }}
    {{ ['-t', item.type] | join if item.type else '' }}
    -q"
  environment:
    PATH: "{{ awscli_env }}/bin"
  args:
    chdir: "{{ igenomes_dir }}"
    creates: "{{ igenomes_dir }}/references/{{ item.genome }}/{{ item.source }}/{{ item.build }}"
  with_items:
    - "{{ igenomes }}"
