
- name: create directories for {{ pipeline }} singularity images
  file:
    path: "{{ container_dir }}"
    state: directory

- name: Create temp directories for singularity images
  file:
    path: "{{ cachedir }}"
    state: directory
  with_items:
    - "{{ nf_core_vars.APPTAINER_CACHEDIR }}"
    - "{{ nf_core_vars.APPTAINER_TMPDIR }}"
  loop_control:
    loop_var: cachedir

- name: nf-core download {{ pipeline }} {{ release }}
  command: >
    nf-core -v
    pipelines download {{ repository }}
    --download-configuration yes
    --compress none
    --outdir {{ sw_path }}/{{ pipeline }}
    --revision {{ release }}
    --container-system singularity
    --container-cache-utilisation amend
    --parallel-downloads 4
  environment: "{{ nf_core_vars }}"
  ignore_errors: true
  args:
    chdir: "{{ sw_path }}"
    creates: "{{ release_path }}"

- name: pull pipeline-specific images for {{ pipeline }} {{ release }}
  command: "singularity pull --name nfcore-{{ container.0 }}.{{ container.1 }}.img {{ nf_core_container_repo }}/{{ container.0 | replace('-', ':', 1) }}.{{ container.1 }}"
  environment: "{{ nf_core_vars }}"
  args:
    chdir: "{{ container_dir }}"
    creates: "{{ container_dir }}/nfcore-{{ container.0 }}.{{ container.1 }}.img"
  ignore_errors: true
  with_nested:
    - "{{ pipeline_specific_containers }}"
    - "{{ pipeline_genomes }}"
  loop_control:
    loop_var: container

- name: create nf-core {{ pipeline }} {{ release }} config
  template:
    src: "site.config.j2"
    dest: "{{ ngi_pipeline_conf }}/{{ pipeline }}_{{ site }}.config"

# TODO remove --igenome_base once all our pipelines uses a template version
# that addresses https://github.com/nf-core/tools/issues/3430
- name: set alias for pipeline {{ pipeline }} {{ release }}
  lineinfile:
    dest: "{{ ngi_pipeline_conf }}/{{ bash_env_script }}"
    line: >
          alias {{ pipeline }}='nextflow run {{ release_path }}/
          -profile uppmax
          -c {{ ngi_pipeline_conf }}/nextflow_miarka_{{ site }}.config
          -c {{ ngi_pipeline_conf }}/{{ pipeline }}_{{ site }}.config
          --igenomes_base /sw/data/igenomes/'
    backup: no

- name: check if pipeline-specific include exists
  local_action:
    module: stat
    get_attributes: no
    get_checksum: no
    get_mime: no
    path: "{{ role_path }}/tasks/{{ pipeline }}_include.yml"
  register: include_stat

- name: execute pipeline-specific includes
  include_tasks: "{{ pipeline }}_include.yml"
  when: include_stat.stat.exists

- name: Remove singularity cache directories
  file:
    name: "{{ cachedir }}"
    state: absent
  with_items:
    - "{{ nf_core_vars.APPTAINER_CACHEDIR }}"
    - "{{ nf_core_vars.APPTAINER_TMPDIR }}"
  loop_control:
    loop_var: cachedir

- name: Create Delivery READMEs for {{ pipeline }} and add to TACA resources
  template:
    src: "{{ readme }}.j2"
    dest: "{{ ngi_resources }}/TACA/{{ site }}/{{ readme }}"
  when: site == "upps"
  with_items:
    - "{{ nf_core_delivery_readmes[pipeline] | default([]) }}"
  loop_control:
    loop_var: readme

- name: store {{ pipeline }} version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "{{ pipeline }}: {{ release }}"
