java_home: /sw/comp/java/OpenJDK_17+35/miarka/
nextflow_java: "{{ java_home }}"
nextflow_version_tag: 24.10.4
nextflow_download_url: https://github.com/nextflow-io/nextflow/releases/download/v{{ nextflow_version_tag }}/nextflow
nf_schema_version: 2.1.1
nextflow_local_env:
  NXF_HOME: "{{ nextflow_dest }}/workfiles"
  NXF_OPTS: -Xms1g -Xmx3500m
  NXF_JAVA_HOME: "{{ nextflow_java }}"
  NXF_PLUGINS_DIR: "{{ nextflow_dest }}/workfiles/plugins"
  PATH: "{{ tools_path.PATH }}"
nextflow_env:
  NXF_HOME: "{{ nextflow_dest }}/workfiles"
  NXF_LAUNCHER: "$PWD/work"
  NXF_TEMP: "{{ ngi_pipeline_nobackup }}/nextflow/temp"
  NXF_WORK: "{{ ngi_pipeline_nobackup }}/nextflow/work"
  NXF_OPTS: -Xms1g -Xmx3500m
  NXF_JAVA_HOME: "{{ nextflow_java }}"
  NXF_PLUGINS_DIR: "{{ nextflow_dest }}/workfiles/plugins"
  NXF_SINGULARITY_HOME_MOUNT: true
  PATH: "{{ tools_path.PATH }}"
nextflow_plugins:
  - name: nf-validation
    version: 1.1.2
  - name: nf-prov
    version: 1.2.1
  - name: nf-tower
    version: 1.6.3
  - name: nf-schema # Will replace nf-validation once we update all our pipelines
    version: "{{ nf_schema_version }}"
